# Generated by Django 4.2.8 on 2023-12-30 11:54

import ckeditor.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255,
                                          verbose_name="Name")),
                (
                    "is_sub_category",
                    models.BooleanField(default=False,
                                        verbose_name="Sub Category"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=255,
                                     unique=True,
                                     verbose_name="Slug"),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=30,
                                     unique=True,
                                     verbose_name="Code"),
                ),
                ("valid_from",
                 models.DateTimeField(verbose_name="Valid From")),
                ("valid_until",
                 models.DateTimeField(verbose_name="Valid Until")),
                (
                    "discount",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(99),
                        ],
                        verbose_name="Discount",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Active"),
                ),
            ],
            options={
                "verbose_name": "Discount",
                "verbose_name_plural": "Discounts",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_paid",
                 models.BooleanField(default=False, verbose_name="Paid")),
                (
                    "discount",
                    models.IntegerField(blank=True,
                                        default=None,
                                        null=True,
                                        verbose_name="Discount"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True,
                                         verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True,
                                         verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "ordering": ["is_paid", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255,
                                          verbose_name="Name")),
                (
                    "description",
                    ckeditor.fields.RichTextField(verbose_name="Description"),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2,
                                        max_digits=7,
                                        verbose_name="Price"),
                ),
                ("image", models.ImageField(upload_to="",
                                            verbose_name="Image")),
                (
                    "is_available",
                    models.BooleanField(default=True,
                                        verbose_name="Available"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True,
                                         verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True,
                                         verbose_name="Updated At"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=255,
                                     unique=True,
                                     verbose_name="Slug"),
                ),
                (
                    "category",
                    models.ManyToManyField(
                        related_name="products",
                        to="shop.category",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1,
                                                verbose_name="Quantity"),
                ),
                ("price", models.PositiveIntegerField(verbose_name="Price")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="shop.order",
                        verbose_name="Order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="shop.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "OrderItem",
                "verbose_name_plural": "OrderItems",
            },
        ),
    ]
